### ISSUE TITLE
Feature Request: Hidden field support

### ISSUE THREAD

**Issue by stuporglue** [kodie/gravityforms-repeater#2]
Hi Kodie, 

Thanks for the nice plugin. Are hidden fields supported? They're not on the list of supported field types but should be able to be handled in a very similar fashion to regular input fields. 

Thanks,
Michael Moore

**Comment by kodie** [comment]
Hey Michael! Thank you for the feedback! I completely forgotten about the hidden field type and just did a quick test to see if it works with my plugin. The good news is that it works fine! The only downside is that when you go to view the entry on the back-end the hidden field doesn't have a label because the label is pulled from the 'gfield_label' which hidden fields do not have.

I have plans to change the way labels are pulled for fields in the near future but until then we'll just have to settle for label-less hidden fields.

**Comment by stuporglue** [comment]
Thanks for the quick response.

> I have plans to change the way labels are pulled for fields in the near future but until then we'll just have to settle for label-less hidden fields

This is great to hear. I saw that and was a bit concerned about it since labels tend to change sometimes. It'd be nice to have something more permanent be used like Parameter Name or at least Admin Label, or whatever you're thinking of.

**Comment by kodie** [comment]
Support for hidden fields were added in the e232ee0 commit and will be in the next release.
